### ISSUE TITLE
Document assert-violation test case and detector

### ISSUE THREAD

**Issue by arturoBeccar** [CoinFabrik/scout-soroban#100]
## Description
Document assert-violation test case and detector

## Subtasks
- [ ] Add minimal vulnerability documentation at the bottom of the README.md in `test-cases`. Use as reference previous scout documentation of vulnerabilities in other blockchains [link](https://coinfabrik.github.io/scout/docs/vulnerabilities). Only use reference up to Severity.
- [ ] Add detector documentation in a README.md in `detectors/DETECTOR_NAME` following the pattern of previous detectors.
- [ ] Add new detector line to Detectors table in main README.md

## Estimate
1
