### ISSUE TITLE
Add detector and test_cases dos-unexpected-revert-with-map

### ISSUE THREAD

**Issue by arturoBeccar** [CoinFabrik/scout-soroban#251]
# Problem Description

Be careful about the usage of `Map`, it is not the same as a `Mapping` in Soroban, and has similar storage limitations to `Vec`. To implement a `Mapping` equivalent, define an appropriate dictionary structure with `Enum`.

If using `Map`, make sure that authorization is required to add new elements, since this structure has storage limitations that could lead to a Denial of Service.

# Tasks

- [ ] Add new detector. Follow the same pattern as dos-unexpected-revert-with-vector, but check for usage of `Map` instead of `Vec`.

![dos-unexpected-refert-with-map](https://github.com/CoinFabrik/scout-soroban/assets/107512933/b23a7338-cfef-4c72-82f8-13338d205793)

- [ ] Add vulnerable test case, using `Map`, for example, to count votes.
- [ ] Add remediated test case solving the issue with a require auth.
- [ ] Add remediated test case using a dictionary structure with `Enum.
- [ ] Add detector documentation
